name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    env:
      OWNER: Azzonya
      IMAGE: mb-feedback
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false

      - run: go mod download

      - run: make

      - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $ --password-stdin

      - run: docker build -t ghcr.io/$OWNER/$IMAGE:latest .

      - run: docker push ghcr.io/$OWNER/$IMAGE:latest

#      - name: Deploy
#        run: curl -f -k -X POST https://pr.zeon.mdev.kz/api/webhooks/aec6884c-9eba-4e26-ba6a-0a2379e5b24a